### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by klasrocket** [jaw0/littlebox-power-inverter#1]
hi.

been looking into this project to try to find what the lower limit for input voltage is, or maybe its only efficiency dropping?
while looking around I realized that there are 3 different output filters, are they just differnt iterations or is each one for a specific kind of load?
hope you got some time to help me clarify this.

**Comment by jaw0** [comment]
the viper chip that steps the voltage down to 12V has a minimum (you'll have to look it up). in testing, I bypassed that and ran it on 12V, not efficient, but functional.

the different filters were just testing to get it smaller, still but good enough.

**Comment by klasrocket** [comment]
Thanks for the previous clarifications! I still have not got to the point of starting to build a unit but just revisited this project again.
I have another question that I hope you might want to help me answering.
Do you think it would it be possible to run 3 of your inverters in sync with 120deg offset for 3phase output? My idea is to use some of the unused pins for serial communication, and let 1 of the inverters send the variable "cycle_step" to the other 2 instead of letting them increment that locally.
